name: Dockerized Builder for Statically-Linked XMRig with Embedded Config using XMRig-Proxy
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * */1'
  #[workflow_call]
  push:
    branches: [ "pgo" ]
  pull_request:
    branches: [ "pgo" ]

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path:             "repo"

    - name: Checkout Main Submodule
      uses: actions/checkout@v3
      with:
        fetch-depth:       1
        path:              main
        ref:               main
        submodules:        true
      env:
        NESTED_SUBMODULES: true

    - name: Checkout AirCrack-NG Submodule
      uses: actions/checkout@v3
      with:
        repository: InnovAnon-Inc/aircrack
        fetch-depth:       1
        path:              acng
        ref:               main
    
    - name: Move AirCrack-NG into Place
      run: |
        mv -v  acng/aircrack-ng                \
               acng/.github/config/nehalem.env \
               main/Config_default.h           \
               main/.github/config/xmrig.env   \
               repo/
        rm -fr acng main

    - name: Load Environment Variables
      working-directory: "repo"
      run: |
        sed 's/^ *#/d; /^ *$/d' *.env | while read -r line ; do export $line ; done

    - name: Bump version and push tag
      id:   tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    #- name: Release
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #    fail_on_unmatched_files: true
    #    generate_release_notes: true
    #    files: |
    #      repo/dist/*

    # TODO new image
    - name: Authenticate with Docker Hub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      working-directory: "repo"
      run: |
        docker build -t "innovanon/xmrig-pgo:$TEAMHACK_VERSION" .
      env:
        TEAMHACK_VERSION: ${{ steps.tag_version.outputs.new_tag }}

    - name: Tag Docker Image
      run: |
        docker tag      "innovanon/xmrig-pgo:$TEAMHACK_VERSION" \
                         innovanon/xmrig-pgo:latest
      env:
        TEAMHACK_VERSION: ${{ steps.tag_version.outputs.new_tag }}

    - name: Deploy Docker Image
      run: |
        docker push      innovanon/xmrig-pgo

    # TODO new image
    - name: Configure GPG Key
      run: |
        echo -n "$GPG_SIGNING_KEY" | gpg --import
        #echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    - name: Sign Installation Package
      working-directory: "repo"
      run: |
        gpg --yes --detach-sig Dockerfile
        gpg --yes --detach-sig docker-compose.yaml
        gpg --yes --detach-sig Config_default.h
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          repo/*

